---
title: "Vehicle Service Data Prep Practice"
output: html_notebook
---

##Loading the data

```{r}
getwd()
setwd("2020-12-19 P23-VehicleService/2. Prepared Data")

d <- read.csv("VehicleService.csv", sep=";")

nrow(d)
```

Checking the Colnames and making the head var

```{r}
colnames(d)

h <- head(d)

```

Check the NAs, Length
```{r}

nrow(d[is.na(d$CustomerID),])

for(i in 1:ncol(d)){
  print(nrow(d[which(is.na(i)),]))
  print(nrow(d[which(is.na(i)),]))
}

nchar(d[1,2])
d[1,2]
unique(nchar(d[,2]))

nrow(d[nchar(d[,2]) == 0,])
d[nchar(d[,2]) == 0,]

question1 <- d[c(203973:203975),]

d[c(203973:203975),]

```


```{r}
d[c(203973:203976),]

d[c(203974),5] <- d[c(203974),6]
d[c(203974),6] <- d[c(203975),1]

d <- d[-203975,]

rownames(d) <- NULL
```

## Checking if dates are correct

```{r}

unique(nchar(d[,2]))

nrow(d[-grep("[0000-00-00]",d$CustomerSince),])

head(d[-grep("^(19[0-9]{2}|2[0-9]{3})-(0[1-9]|1[012])-([123]0|[012][1-9]|31)$",d$CustomerSince),])

question2 <- d[407989,]

d[407989,2] <- "1999-04-30"
```

## Checking numbers
```{r}
nrow(d[!is.numeric(d$X2014),])
nrow(d[!as.numeric(d$X2015),])
nrow(d[!is.numeric(d$X2016E),])

unique(nchar(d$X2015))

head(d[-grep("^([0-9]|[0-9]{2}|[0-9]{3}|).([0-9]{2})$",d$d$X2015),])
nrow(d[nchar(d$X2015) == 1,])
d[nchar(d$X2015) == 1,]

question3 <- d[is.na(as.numeric(d$X2015)),]

d[is.na(as.numeric(d$X2015)),] <- gsub("$", ".", d[is.na(as.numeric(d$X2015)),5], fixed = T)


d[676803,5] <- gsub("$", ".", d[676803,5], fixed = T)

d$X2015 <- as.numeric(d$X2015)

head(d)

#sum should be 419,896,187.87
options(digits=12)
sum(round(d$X2016E,3))

```

## Checking the Vehicle

```{r}
unique(nchar(d$Vehicle))

nrow(d[!grep("([0-9]{4}) .*",d$Vehicle),])


sort(unique(substr(d$Vehicle,1,4)))
```


Histograms for numerical params

```{r}
hist(d$X2014,breaks = 10)
nrow(d[is.na(d$X2014),"X2014"])
hist(round(d[which(!is.na(d$X2014) & d$X2014 < 5000),"X2014"],-1))

head(table(round(d[which(!is.na(d$X2014) & d$X2014 < 5000),"X2014"],1)))

max(d[!is.na(d$X2014),"X2014"])
```



```{r}
max(d[!is.na(d$X2014),"X2014"])

summary(d$X2014)

nrow(d[d$X2014 == 0,])

head(d[d$X2014 == 0,])

test <- d[which(d$X2014 == 0),]

nrow(d)

nrow(d[which(as.double(substr(d$CustomerSince,1,4)) >= 2014),])

sort(unique(substr(d$CustomerSince,1,4)))

nrow(d[which(as.double(substr(d$Vehicle,1,4)) != 2015 & d$X2014 == 0),])

d[which(as.double(substr(d$Vehicle,1,4)) != 2015 & d$X2014 == 0),]

```


Check uniqness of Customer Id

```{r}
c(length(unique(d$CustomerID)), nrow(d))

id_counts <- data.frame(table(d$CustomerID))

head(id_counts[which(id_counts$Freq > 1),])

d[d$CustomerID == 3490750,]
question4 <- d[955906:955908,]

?table

```



Checking the Predicted values

```{r}

nrow(d[d$X2015 == 0,])
nrow(d[d$X2016E == 0,])

d[d$X2016E == 0,]

head(round(d$X2016E, -1))
hist(round(d$X2016E, -1))
hist(round(d$X2015, -1))
hist(round(d$X2014, -1))


max(d[!is.na(d$X2014),"X2014"])

nrow(d[which(d$X2014 == 20000),])

question5 <- d[which(d$X2014 == 20000),]

hist(d[-902807,"X2014"])

```


